baseurl:
permalink: pretty
markdown: kramdown
paginate: 5
repo: maptimenyc.github.io
github_org: maptimenyc
maptime:
  chapter: Maptime NYC
  twitter: MaptimeNYC
  #disqus: YOUR DISQUS USERNAME
highlighter: pygments
